name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup .netrc for Hugging Face Authentication
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "machine huggingface.co login ${HF_TOKEN} password x" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Clone Hugging Face Space Repository
        env:
          HF_REPO: kohlin/nlp-spacy  # Replace with your Hugging Face Space repository name.
        run: |
          git clone https://huggingface.co/${HF_REPO}.git space-repo

      - name: Copy Files to Hugging Face Space Repo
        run: |
          rsync -av --exclude='.git' ./ space-repo/

      - name: Commit and Push Changes to Hugging Face Space
        env:
          HF_REPO: kohlin/nlp-spacy
        run: |
          cd space-repo
          git add .
          git commit -m "Deploy updated app from GitHub Actions" || echo "No changes to commit"
          git push https://huggingface.co/${HF_REPO}.git